spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  datasource:
    url: jdbc:mysql://localhost:3306/feed_db
    username: root
    password: 9462
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: feed-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feed-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.threads.events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084